import { ThemeProvider } from "@/components/theme-provider"
import type { Metadata } from "next";

import "./globals.css";
import { DM_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";



const font = DM_Sans({subsets:['latin']})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        <ClerkProvider>
          <body
            className={`${font.className}  antialiased`}
          >  <img
          src="/background.png"
          alt="Background"
          className="absolute top-0 left-0 w-full  object-cover opacity-50 -z-10 h-full"
        />

            {children}
          </body>
        </ClerkProvider>
      </ThemeProvider>
    </html>
  );
}
